spring.application.name=oauth2-github

server.port=8083

spring.security.oauth2.client.registration.github.client-id=Ov23litgyPCNQAoyZqjk
spring.security.oauth2.client.registration.github.client-secret=86a78cd7913df6a0fd33028c474dbb5f5935558c
